language: java
jdk:
- oraclejdk8
before_install:
- rvm use 2.3.1 --install --binary --fuzzy
- nvm install stable
- npm install -g bower
install:
- bundle install
- npm install
- npm run bower
script:
- npm run test
